// AUTH ACTION TYPES

export const REQUEST_SEND = 'REQUEST_SEND'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'


// ALERT ACTION TYPES

export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_FAILURE = 'ALERT_FAILURE'
export const ALERT_INFO = 'ALERT_INFO'


// Verification action types

export const ACCOUNT_VERIFICATION_SUCCESS = 'ACCOUNT_VERIFICATION_SUCCESS'
export const ACCOUNT_VERIFICATION_FAILURE = 'ACCOUNT_VERIFICATION_FAILURE'


// JWT actions types

export const JWT_TOKEN_WRONG = 'JWT_TOKEN_WRONG';



// ADMIN USER ACTIONS

export const ADMIN_GET_USER_BY_ID = 'ADMIN_GET_USER_BY_ID'
export const ADMIN_GET_ALL_USERS = 'ADMIN_GET_ALL_USERS'
export const ADMIN_EDIT_USER = 'ADMIN_EDIT_USER'
export const ADMIN_DELETE_USER = 'ADMIN_DELETE_USER'